extensions:
  health_check: {}

receivers:
  collectd:
      default_attributes_prefix: "dap_"

exporters:
  logging: {}
  #signalfx:
  #  auth_token: "N6Ffwg0u2t07U_vGYoi7kQ"
  #  realm: "us1"
  #signalfx:
  #  auth_token: "N6Ffwg0u2t07U_vGYoi7kQ"
  #  realm: "us1"
  # prometheus:
  #  endpoint: "127.0.0.1:5555"
  # opencensus:
  #  endpoint: "127.0.0.1:55678"

processors:
  #queued-retry: {}
  batch: {}
  #probabilistic-sampler:


service:
  # extensions: [health_check]
  pipelines:
    metrics:
      receivers: [collectd]
      processors: []
      exporters: [logging]
