extensions:
  health_check: {}
receivers:
  memorymonitor:
    scrape_interval: 5s
exporters:
  # logging: {}
  prometheus:
    endpoint: "127.0.0.1:5555"
  # opencensus:
  #  endpoint: "127.0.0.1:55678"

processors: {}
  #queued-retry: {}
  #batch: {}
  #probabilistic-sampler:


service:
  # extensions: [health_check]
  pipelines:
    metrics:
      receivers: [memorymonitor]
      exporters: [prometheus]
