receivers:
  zipkin: {} 
  jaeger: {}
  opencensus: {}
exporters:
  # zipkin: {}
  logging: {}
  opencensus:
    # endpoint: "127.0.0.1:55678"
    endpoint: "testhost:55678"

processors:
  attributes: {} 
  batch: {}
  #probabilistic-sampler:
  #disabled: true


service:
  pipelines:
    traces:
      receivers: [zipkin]
      processors: [batch]
      exporters: [opencensus]
